---
# yamllint disable rule:line-length
name: Typos

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: typos-action
        uses: crate-ci/typos@v1.12.5
